- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_info:
      cloud: openstack
    register: result
    tags:
      - osp.smoke
      
#  - name: Curl website
#    shell: "curl http://{{ item.public_v4 }}"
#    register: webpage
#    loop: "{{result.openstack_servers}}"
#    when: item.metadata.group  == "frontends"
#    tags:
#      - osp.smoke
#
#  - name: Fail if 'Ansible has done its job' is not in the page content
#    fail:
#    when: '"Ansible has done its job" not in webpage.stdout' # Curl answer the contents in stdout.
#    tags:
#      - osp.smoke

- name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
  uri:
    url: http://{{ item.public_v4 }}
    return_content: yes
   loop: "{{result.openstack_servers}}"
   when: item.metadata.group  == "frontends"
   tags:
     - osp.smoke
  register: this
  failed_when: "'Ansible has done its job' not in this.content"
