- hosts: workstation
  gather_facts: true
  roles:
  - name: osp_facts

# Setup front-end load balancer tier


- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - {name: base_config, tags: base-config}
    - {name: lb_tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  gather_facts: true
  roles:
    - {name: base_config, tags: base-config}
    - {name: app_tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - {name: base_config, tags: base-config}
    - {name: db_tier, tags: [dbs, postgres]}
