---
- name: Install Tomcat package(s)
  package:
    name: "{{ payload }}"
    state: present

- name: Copy jar file into tomcat bin
  copy:
    src: /usr/share/java/tomcat/extras/tomcat-juli.jar
    dest: /usr/share/tomcat/bin/tomcat-juli.jar
    remote_src: yes

- name: Enable Tomcat at boot
  service:
    name: tomcat
    enabled: yes

- name: Create Tomcat content directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: Copy static index.html to tomcat webapps/ansible/index.html
  template:
    src: templates/index.html.j2
    dest: /usr/share/tomcat/webapps/ROOT/index.html
    mode: 0644

- name: Start Tomcat
  service:
    name: "{{ payload }}"
    state: started
