---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    cloud: openstack
  register: result


- name: Delete all instances
  os_server:
    cloud: openstack
    name: "{{ item.name }}"
    state: absent
    timeout: 200
  with_items: "{{result.openstack_servers}}"